[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
aurum_hybrid_pricing = "FJqGn3dLCFz95Xxg36RXUii3WiuDPtmw4iBfNLtE6vM7"

[programs.mainnet]
aurum_hybrid_pricing = "FJqGn3dLCFz95Xxg36RXUii3WiuDPtmw4iBfNLtE6vM7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"  # switched to mainnet deployment target
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
